version: '3.9'

services:
  brain-stroke-detector:
    build:
      context: .
      dockerfile: Dockerfile
    image: peco602/brain-stroke-detector:latest
    container_name: brain-stroke-detector
    expose:
      - "8080"
      - "8501"
    ports:
      - "8080:8080"
      - "8051:8051"
