apiVersion: v1
kind: Service
metadata:
  name: brain-stroke-detector
spec:
  type: LoadBalancer
  selector:
    app: brain-stroke-detector
  ports:
  - name: flask
    port: 8000
    targetPort: 8080
  - name: streamlit
    port: 8001
    targetPort: 8051
